// The names of GTA IV's pad controls in ePadControls order (IV-SDK), without their INPUT_ prefix: help texts
// name the control they ask for as ~INPUT_<NAME>~ (Missions.cpp). Generated from ePadControls.h.
#pragma once

namespace lc::pad
{
	inline constexpr const char* kControlNames[] = {
		"NEXT_CAMERA", "SPRINT", "JUMP", "ENTER", "ATTACK", "ATTACK2", "AIM", "LOOK_BEHIND", "NEXT_WEAPON", "PREV_WEAPON",
		"NEXT_TARGET_LEFT", "NEXT_TARGET_RIGHT", "MOVE_LEFT", "MOVE_RIGHT", "MOVE_UP", "MOVE_DOWN", "LOOK_LEFT",
		"LOOK_RIGHT", "LOOK_UP", "LOOK_DOWN", "DUCK", "PHONE_TAKE_OUT", "PHONE_PUT_AWAY", "PICKUP", "SNIPER_ZOOM_IN",
		"SNIPER_ZOOM_OUT", "SNIPER_ZOOM_IN_ALTERNATE", "SNIPER_ZOOM_OUT_ALTERNATE", "COVER", "RELOAD", "VEH_MOVE_LEFT",
		"VEH_MOVE_RIGHT", "VEH_MOVE_UP", "VEH_MOVE_DOWN", "VEH_GUN_LEFT", "VEH_GUN_RIGHT", "VEH_GUN_UP", "VEH_GUN_DOWN",
		"VEH_ATTACK", "VEH_ATTACK2", "VEH_ACCELERATE", "VEH_BRAKE", "VEH_HEADLIGHT", "VEH_EXIT", "VEH_HANDBRAKE",
		"VEH_HANDBRAKE_ALT", "VEH_HOTWIRE_LEFT", "VEH_HOTWIRE_RIGHT", "VEH_LOOK_LEFT", "VEH_LOOK_RIGHT", "VEH_LOOK_BEHIND",
		"VEH_CIN_CAM", "VEH_NEXT_RADIO", "VEH_PREV_RADIO", "VEH_HORN", "VEH_FLY_THROTTLE_UP", "VEH_FLY_THROTTLE_DOWN",
		"VEH_FLY_YAW_LEFT", "VEH_FLY_YAW_RIGHT", "MELEE_ATTACK1", "MELEE_ATTACK2", "MELEE_ATTACK3", "MELEE_KICK",
		"MELEE_BLOCK", "FRONTEND_DOWN", "FRONTEND_UP", "FRONTEND_LEFT", "FRONTEND_RIGHT", "FRONTEND_RDOWN", "FRONTEND_RUP",
		"FRONTEND_RLEFT", "FRONTEND_RRIGHT", "FRONTEND_AXIS_X", "FRONTEND_AXIS_Y", "FRONTEND_RIGHT_AXIS_X",
		"FRONTEND_RIGHT_AXIS_Y", "FRONTEND_PAUSE", "FRONTEND_ACCEPT", "FRONTEND_CANCEL", "FRONTEND_X", "FRONTEND_Y",
		"FRONTEND_LB", "FRONTEND_RB", "FRONTEND_LT", "FRONTEND_RT", "MELEE_ATTACK4", "ZOOM_RADAR", "FREE_AIM", "MOUSE_UD",
		"MOUSE_LR", "MOVE_KEY_FB", "MOVE_KEY_LR", "MOVE_KEY_STUNTJUMP", "MOUSE_WHEEL_UP", "MOUSE_WHEEL_DOWN",
		"FRONTEND_AXIS_UD", "FRONTEND_AXIS_LR", "FRONTEND_LEGEND", "FRONTEND_APPLY", "FRONTEND_SHOWSCORE", "WEAPON_UNARMED",
		"WEAPON_MELEE", "WEAPON_HANDGUN", "WEAPON_SHOTGUN", "WEAPON_SMG", "WEAPON_RIFLE", "WEAPON_SNIPER", "WEAPON_HEAVY",
		"WEAPON_THROWN", "WEAPON_SPECIAL", "VEH_KEY_UD", "VEH_KEY_LR", "VEH_NEXT_WEAPON", "VEH_PREV_WEAPON",
		"TURN_OFF_RADIO", "FRONTEND_MINIGAME_1", "FRONTEND_MINIGAME_2", "FRONTEND_MINIGAME_3", "FRONTEND_MINIGAME_4",
		"FRONTEND_MODEL_SCREEN", "FRONTEND_VEHICLE_TOGGLE", "FRONTEND_DELETE_FILTER", "FRONTEND_REFRESH",
		"FRONTEND_PLAYER_LIST", "TEXT_CHAT_TOGGLE", "TEXT_CHAT_TEAM", "TEXT_CHAT_UNIVERSAL", "TEXT_CHAT_RESULTS_TOGGLE",
		"TEXT_CHAT_Y", "FRONTEND_LOCK_LOBBY", "KB_UP", "KB_DOWN", "KB_LEFT", "KB_RIGHT", "NEXT_TRACK", "PREV_TRACK",
		"DROP_WEAPON", "MOUSE_LMB", "MOUSE_RMB", "FE_MOUSE_UD", "FE_MOUSE_LR", "VEH_FLY_PITCH_UP", "VEH_FLY_PITCH_DOWN",
		"VEH_FLY_ROLL_LEFT", "VEH_FLY_ROLL_RIGHT", "REPLAY_PLAY", "REPLAY_SAVE_TO_HDD", "REPLAY_LOAD_FROM_HDD",
		"REPLAY_EXIT", "FRONTEND_MARKER_DELETE", "FRONTEND_REPLAY_PAUSE", "FRONTEND_REPLAY_REWIND", "FRONTEND_REPLAY_FFWD",
		"FRONTEND_REPLAY_NEWMARKER", "FRONTEND_REPLAY_RECORD", "FRONTEND_REPLAY_SCREENSHOT", "FRONTEND_REPLAY_HIDEHUD",
		"FRONTEND_REPLAY_STARTPOINT", "FRONTEND_REPLAY_ENDPOINT", "FRONTEND_REPLAY_ADVANCE", "FRONTEND_REPLAY_BACK",
		"FRONTEND_REPLAY_SHOWHOTKEY", "FRONTEND_REPLAY_TOOLS", "FRONTEND_REPLAY_RESTART", "FRONTEND_REPLAY_CYCLEMARKERLEFT",
		"FRONTEND_REPLAY_CYCLEMARKERRIGHT", "FRONTEND_AXIS_FWD", "FRONTEND_AXIS_BACK", "FRONTEND_AXIS_LEFT",
		"FRONTEND_AXIS_RIGHT", "FRONTEND_DEFINITION", "FRONTEND_F6", "FE_REPLAY_TOGGLETIME", "FE_REPLAY_TOGGLETIPS",
		"FE_REPLAY_PREVIEW", "FRONTEND_PASTE", "FRONTEND_CUT", "FRONTEND_COPY", "VOICE_CHAT", "SNIPER_ZOOM_IN_KB",
		"SNIPER_ZOOM_OUT_KB", "KB_PHONE_ACCEPT", "KB_PHONE_CANCEL", "VEH_ATTACK3_KB", "DETONATE", "VEH_MOVE_LEFT_2",
		"VEH_MOVE_RIGHT_2",
	};
	inline constexpr int kControlCount = static_cast<int>(sizeof(kControlNames) / sizeof(kControlNames[0]));
}
